{% set name = "xlens" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mr-superonion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a7cc9a4c5036e128f4ae17a326fc9a249f5708c52583b8a376b7a7c23f3356f3


build:
  number: 0
  skip: True   # [py<311 or py>311 or win or osx]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"



requirements:
  host:
    - python
    - setuptools >=38
    - setuptools_scm
    - pip
  run:
    - python ==3.11
    - lsstdesc-wl-shear-sims ==0.4.4
    - anacal ==0.5.1
  

test:
  imports:
    - xlens
  requires:
    - stackvana 

about:
  home: https://github.com/mr-superonion/xlens
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Graviational Lensing from Image Pixels"
  description: |
    Xlens is a open-source software to simulate gravitational lensed image and run 
    shear calibration methods.

extra:
  recipe-maintainers:
    - mr-superonion
    - zhouconghao
