{% set name = "xlens" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mr-superonion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d856b942c15c3c5e238070a9af67739b4cf29a36e408e382ca1b4d3fc373f472


build:
  number: 0
  skip: true  # [py<311 or py>311 or win or osx]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"



requirements:
  host:
    - python
    - setuptools >=38
    - setuptools_scm
    - pip
  run:
    - python ==3.11
    - lsstdesc-wl-shear-sims ==0.4.4
    - anacal =={{ version }}


test:
  imports:
    - xlens
  requires:
    - stackvana

about:
  home: https://github.com/mr-superonion/xlens
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Graviational Lensing from Image Pixels"
  description: |
    Xlens is a open-source software to simulate gravitational lensed image and run 
    shear calibration methods.

extra:
  recipe-maintainers:
    - mr-superonion
    - zhouconghao
