{% set name = "xlens" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mr-superonion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ca666f031bfba98ead505429d55870980646e0e599b457cf4560dc88ba469f1f


build:
  number: 0
  skip: true  # [py<311 or py>313 or win or osx]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"



requirements:
  host:
    - python
    - setuptools >=38
    - setuptools_scm
    - pip
  run:
    - python ==3.11
    - anacal ==0.7.3


test:
  imports:
    - xlens
  requires:
    - stackvana

about:
  home: https://github.com/mr-superonion/xlens
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Graviational Lensing from Image Pixels"
  description: |
    Xlens is a open-source software to simulate gravitational lensed image and run 
    shear calibration methods.

extra:
  recipe-maintainers:
    - mr-superonion
    - zhouconghao
